"""Regenerate docs/assets/js/media.js: {slug: [w, h]} for every docs/media/<slug>-1600.webp.

Run from the repo root after adding or replacing images:
    python scripts/media_manifest.py
New images are expected as a pair: <slug>-1600.webp (long edge <= 1600) and <slug>-640.webp.
"""
from pathlib import Path
import json

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
MEDIA = ROOT / "docs" / "media"
OUT = ROOT / "docs" / "assets" / "js" / "media.js"

dims = {}
for f in sorted(MEDIA.glob("*-1600.webp")):
    slug = f.name[: -len("-1600.webp")]
    with Image.open(f) as im:
        dims[slug] = list(im.size)
    if not (MEDIA / f"{slug}-640.webp").exists():
        print(f"warning: missing {slug}-640.webp")

OUT.write_text(
    "/* generated by scripts/media_manifest.py - image sizes for layout */\n"
    "window.MEDIA = " + json.dumps(dims, separators=(",", ":")) + ";\n",
    encoding="utf-8",
)
print(f"{len(dims)} images -> {OUT.relative_to(ROOT)}")
